GET http://localhost:5000/api/search/count

###
GET http://localhost:8000/api/level

###
POST http://localhost:8000/api/search/senior
Content-Type: application/json

{
    "page": 4,
    "location": ["Hồ Chí Minh", "Hà Nội"],
    "categories":[
        "Kiến trúc/Thiết kế nội thất"
        ],
            "level": "Nhân Viên"

}